### ISSUE TITLE
Minificar a biblioteca?

### ISSUE THREAD

**Issue by amarildolucas** [usekamba/kamba-checkout-js#10]
Seria um ganho termos a biblioteca minificada usando compressão?

```js
kamba-checkout.min.js
```

Qual seria a melhor abordagem em relação ao rápido carregamento da biblioteca? Que outras táticas poderiam ser usadas?

**Comment by AlexJuca** [comment]
Minificar seria boa opção para diminuir o tamanho da lib e carregar mais rápido. Também usar caching séria bom para minimizar o número de vezes que o cliente baixa a lib.

**Comment by amarildolucas** [comment]
Acredito que podemos adicionar então `minificação` e `caching` da lib no **roadmap**.

**Comment by amarildolucas** [comment]
> Minificar seria boa opção para diminuir o tamanho da lib e carregar mais rápido. Também usar caching séria bom para minimizar o número de vezes que o cliente baixa a lib.

Acredito que podemos adicionar então `minificação` e `caching` da lib no **roadmap**.

**Comment by amarildolucas** [comment]
Rails faz a minificação automaticamente. Remendado ler sobre o asset pipeline. Ainda assim, uma abordagem diferente e melhorada pode ser adicionada. Esta issue continua aberta mas como não prioritária para uma melhoria futura sendo que não bloqueia de nenhuma forma quaisquer funcionalidades do checkout.

**Comment by amarildolucas** [comment]
Rails faz a minificação automaticamente. Como temos a lib hospedada no heroku, o asset pipeline trada deste problema.
