### ISSUE TITLE
Descontinuar hospedagem com RawGit

### ISSUE THREAD

**Issue by amarildolucas** [usekamba/kamba-checkout-js#13]
Descontinuar hospedagem com RawGit devido ao anúncio oficial de descontinuação e suporte para novos repositórios:

https://rawgit.com/

```
RawGit is now in a sunset phase and will soon shut down. It's been a fun five years, but all things must end.

GitHub repositories that served content through RawGit within the last month will continue to be served until at least October of 2019. URLs for other repositories are no longer being served.

If you're currently using RawGit, please stop using it as soon as you can.
```

**Comment by AlexJuca** [comment]
Visto que já estamos a hospedor no próprio servidor estou fechando essa issue.

**Comment by GarciaFreelancer** [comment]
@amarildolucas neste momento não consigo perceber o que falta em relação a esta Issue

**Comment by GarciaFreelancer** [comment]
Como já estamos a hospedar o Checkout Js no servidor com o Merchant-web talvez o mais recomendado seria lançarmos as atualizações (novo design, opções de abrir app etc)  para production, a fim de obtermos tudo por lá, e consequentemente podemos substituir na documentação do Checkout Js a url gerado pelo Rawgit por este "http://comerciante.usekamba.com/checkout/0.0.1/kamba-web-sdk.js"

**Comment by AlexJuca** [comment]
@amarildolucas I think we can close this issue.

**Comment by amarildolucas** [comment]
@GarciaFreelancer @AlexJuca podem enviar-me um link demo para eu testar o fluxo completo e avaliar em relação à esta task antes de prosseguir com o fechamento da issue.

**Comment by amarildolucas** [comment]
Como anteriormente apontado pelo @GarciaFreelancer esta issue estará sendo fechada pois a documentação foi previamente atualizada com dados diferentes do que consta nesta issue.
