### ISSUE TITLE
Melhorar o Checkout KAMBA QR

### ISSUE THREAD

**Issue by amarildolucas** [usekamba/kamba-checkout-js#16]
Criar um design estável, consistente e universal para todas as integrações.

**Comment by amarildolucas** [comment]
Modal atualizado v1 com o design universal parecido ao app móvel a ser aplicado. Mesmas características que o checkout js com mais estilização e organização dos componentes apenas.

![captura de ecra 2018-11-12 as 18 00 38](https://user-images.githubusercontent.com/675211/48372486-e7568700-e6a5-11e8-8b66-cd1dcaffefb0.png)

![kamba-checkout-qr-v01](https://user-images.githubusercontent.com/675211/48372497-f0475880-e6a5-11e8-9e4a-95ed5706e9da.png)

**Comment by GarciaFreelancer** [comment]
@amarildolucas faltando o asset referente a imagem da loja

**Comment by amarildolucas** [comment]
Restante dos assets @GarciaFreelancer 
![kambaweb-lock](https://user-images.githubusercontent.com/675211/48455552-c9bb1780-e7a2-11e8-8d7e-3956afd90eba.png)
![kambaweb-lock 2x](https://user-images.githubusercontent.com/675211/48455553-c9bb1780-e7a2-11e8-9f03-a4618f1351f9.png)
![kambaweb-logo](https://user-images.githubusercontent.com/675211/48455554-ca53ae00-e7a2-11e8-95cd-710ce140981f.png)
![kambaweb-logo 2x](https://user-images.githubusercontent.com/675211/48455555-ca53ae00-e7a2-11e8-9f5a-eb50432d708b.png)
![kambaweb-shop](https://user-images.githubusercontent.com/675211/48455556-ca53ae00-e7a2-11e8-8d96-a9f68c267bd6.png)
![kambaweb-shop 2x](https://user-images.githubusercontent.com/675211/48455557-ca53ae00-e7a2-11e8-8520-40a4d7af45a5.png)

**Comment by AlexJuca** [comment]
Done. closing issue!
