### ISSUE TITLE
Utilidade do método de estilização do botão no Cliente

### ISSUE THREAD

**Issue by amarildolucas** [usekamba/kamba-checkout-js#2]
https://github.com/usekamba/kamba-checkout-js/blob/3e8cf7f8c99634fe281fe233c3a8b2287acd66f0/merchant-web.html#L58

Verifiquei que este método no **script** embutido no body `styleButtonPayKamba();` estiliza o botão. Mas já que eu não tenho controle sobre o método de estilização, não faria mais sentido ter ele abstraído já no código que importo no cabeçalho?

Seria menos uma linha e funcionalidade e passaria mais simplicidade à integração que já é ótima ao facilitar a vida no momento da integração. Mas acredito que se pode facilitar sempre.

**Comment by GarciaFreelancer** [comment]
Boa sugestão Amarildo, o processo para implementação da mesma já está ser feita
