### ISSUE TITLE
Faltando configurar url para sandbox ou production

### ISSUE THREAD

**Issue by AlexJuca** [usekamba/kamba-checkout-js#3]
Actuamente há apenas uma url onde devia existir duas:
1) Um para production
2) Outro para sandbox

Outra coisa é que enviroment não deve ser passado para o header, a api não irá fazer nada com este header.

A lib deve apenas receber o enviroment e usar a url certo para comunicar com a api.

Então isso não está conforme a spec:
``` 
enviroment: 'sandbox',
api_key: 'Token soaO7K9kcFSbG3n0DHaDFwtt'
```
Uma possível solução: 

```javascript
kamba( initial_config = { 
		              channel: 'WEBSITE',
		              currency: 'AOA',
		              initial_amount: 10500,
		              notes: 'Curso API Iniciantes',
		              redirect_url_success: 'http://amarildolucas.com/curso/api-iniciantes',
		              payment_method: 'WALLET'
		            },
		            header =  {
		              api_key: 'soaO7K9kcFSbG3n0DHaDFwtt'
		           },  
		            enviroment = 'sandbox');
	      	}
``` 

A lib irá verificar se o ambiente é "sandbox" ou "production" e retornar o a url certo:
```javascript

if (enviroment == 'sandbox') {
url = "https://sandbox.usekamba.com/v1/checkouts/"
} else {
url = "https://api.usekamba.com/v1/checkouts/"
}
```

**Comment by GarciaFreelancer** [comment]
Certo @AlexJuca , percebido. E já será incluída o reparo
