### ISSUE TITLE
Dynamic link link property fails to open proper intent

### ISSUE THREAD

**Issue by AlexJuca** [usekamba/kamba-checkout-js#30]
The current scheme does not open the correct link for purchases to be made using the PayQRContac 
 activity.

**Comment by AlexJuca** [comment]
The current dynamic link looks like the following: 

```https://usekamba.page.link/?link=https://www.usekamba.com/&apn=com.usekamba.kamba.kamba&ibi=com.usekamba.kamba&mID=${merchantId}&chID=${checkoutId}
```

To open the correct app screen for purchases to be made, link needs to be formatted like such:
```https://usekamba.page.link/?link=https://www.usekamba.com/pay?chID=${checkoutId}&apn=com.usekamba.kamba.kamba&ibi=com.usekamba.kamba
```

**Comment by amarildolucas** [comment]
Sendo que este formato de URL não é usado por não possuir formato universal para ambos aplicatios, este problema não é um problema da biblioteca mas de integração no cliente.
