### ISSUE TITLE
A link formatted in such a way that would allow for the user to perform payments by clicking on the link and open the app directly on both android and iOS.

### ISSUE THREAD

**Issue by AlexJuca** [usekamba/kamba-checkout-js#34]
A link formatted in the following way would allow for the user to perform payments by clicking on the link and open the app directly on both android and iOS.

Link example: 
https://comerciante.usekamba.com/pay?chID=29b674d5-0040-4e69-8aa1-8aa839ab598d

Cons: In the event that the user does not have the app installed, it will not be possible to redirect to the app store or play store.

**Comment by amarildolucas** [comment]
@AlexJuca esta issue já foi realizada?

**Comment by GarciaFreelancer** [comment]
A implementação do link universal já encontra-se no Checkout, penso que temos este problema resolvido

**Comment by amarildolucas** [comment]
Ótimo @GarciaFreelancer, então estou fechando esta issue por já estar resolvida.
