### ISSUE TITLE
QR não centralizado no layout do checkout

### ISSUE THREAD

**Issue by amarildolucas** [usekamba/kamba-checkout-js#36]
![image from ios](https://user-images.githubusercontent.com/675211/50925083-6a8f2180-1438-11e9-9d5c-e0b51f06e6d6.png)

**Comment by amarildolucas** [comment]
@GarciaFreelancer conseguimos corrigir o problema apontado nesta issue?

**Comment by GarciaFreelancer** [comment]
Sim @amarildolucas já foi corrigido esta problema

**Comment by amarildolucas** [comment]
Fechando esta issue uma vez que o problema já foi corrigido.
