### ISSUE TITLE
Porque existe o Type-Key | type_key: 'Token?

### ISSUE THREAD

**Issue by AlexJuca** [usekamba/kamba-checkout-js#4]
No parametro secondary config, qual é a necessidade do usuário passar o type_key? Isso pode ser abstraido. Em nenhum momento o usuário vai mudar este campo.

**Comment by GarciaFreelancer** [comment]
@AlexJuca  já havia abstraído essa parte, mas ao rever as anotações que havia feito sobre reparos constatei que havia uma parte que @amarildolucas  dizia, que nem sempre o prefixo de uma chave seria "Token" e que poderia variar em outras chaves. Mas, no problem pessoal, me certifiquem só que todas as chaves inicialmente apenas serão produzidas com a palavra Token, que já faço o reparo se este for o caso.
