### ISSUE TITLE
Remover "merchant-web.html", exemplo de página HTML da Biblioteca principal

### ISSUE THREAD

**Issue by amarildolucas** [usekamba/kamba-checkout-js#6]
Seguindo à Doc eu posso testar a biblioteca na minha própria página ou criar rapidamente uma página para testes. Remover a página de exemplo, incluindo recursos de imagens ou qualquer recurso não diretamente ligado a biblioteca deixa a biblioteca mais limpa e simples e não confundiria o usuário visitante ao repositório.

É encorajado a não necessidade de baixar o repo para testar na máquina local. Isso em si, valida a ideia de que este exemplo nunca seria usado.

**Comment by GarciaFreelancer** [comment]
Certo Pessoal! Também concordo, todos os recursos não ligados directamente com a biblioteca serão removidos do repo de forma a deixar ela mais compreensível.
