### ISSUE TITLE
Hospedar a API no próprio Servidor

### ISSUE THREAD

**Issue by amarildolucas** [usekamba/kamba-checkout-js#9]
Adicionar links amigáveis para hospedar a API no próprio servidor. Alguns formatos de URL que me pareceram mais simples e claro dependerá da implementação. O ponto é deixar a url mais limpa apenas.

URLs de integração:
```
<!-- sandbox -->
<script src="https://sandbox-comerciante.usekamba.com/checkout/0.0.1/kamba-checkout.js"></script>

<!-- production -->
<script src="https://comerciante.usekamba.com/checkout/0.0.1/kamba-checkout.js"></script>
```

**Comment by GarciaFreelancer** [comment]
Url de integração actual do checkout Js é apenas um exemplar criado a partir do github e rawgit. O nome ou a Url que poderá ser usada oficialmente pode ser definida no momento da hospedagem do repositório. E é desnecessário termos uma Url para sandibox e outro para production, porque o usuário tem a possibilidade de definir o ambiente de uso passando o valor na configuração do environment

**Comment by cabanga** [comment]
Por mi deveriamos levar em conta dois pontos

1. Se para cada integração ter sua página, então o melhor ser desta forma:
https://developers.usekamba.com/v1/kamba-checkout.js

2. Se a descrição das integrações estiverem em uma única página, mas separadas por tabs, melhor seria desta forma:

https://developers.usekamba.com/v1
ou
https://api.usekamba.com/v1
A seguir as tabs de cada implementação

Como referencia https://developer.proxypay.co.ao/v2/

**Comment by amarildolucas** [comment]
@cabanga acredito que foi feita uma confusão entre caminho de api, página ou algo assim...

Mas a questão é apenas hospedagem. O script é um asset estático js. Atualmente ele usa cdn de terceiros para hospedagem e pretende-se hospedar no nosso próprio host.

O caminho padrão já é mesmo o definido diferente de api ele contará por deploys por ser um asset.

A questão é como poderíamos hospedar o script em nosso servidor e ainda assim manter o fluxo de alterações realizadas aqui no Github?

**Comment by AlexJuca** [comment]
@amarildolucas @GarciaFreelancer @cabanga fechando essa issue, visto que já há uma solução.

**Comment by amarildolucas** [comment]
@cabanga @AlexJuca esta issue não está finalizada. Mas como está relacionada com o submódulo que é a última coisa que falta nessa configuração pois de alguma forma a hospedagem está feita, esta issue está sendo fechada e a continuação do fluxo deverá ser feita ou discutida na issue do submódulo.
